name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race ./...

      - name: Build
        run: go build
